[satellites.ASTEP.astropix]

setup_type = "gecco"

outdir = "./"
output_directory_format = "."# "/media/teleuser/4TB/astropix/sr90_astep/data/raw_data"

chip_configs = ["singlechip_v4"]
chips_per_row = [1]
analog_layer = 0
chip_version = 4
use_shift_register = true

injection_row = 0
injection_col = 2
injection_voltage = 1000

threshold = 1200

spi_freq = 1e6
autoread = true
fpga_timestamp_size = 3

