




/*
    Generated by HDL Build
*/
module astep24_3l_top_clocking (
    input  wire sysclk_in,
    input  wire clk_ext,
    input  wire resn,

    output wire global_resn_o, // Reset request to be used by reset sync outside of this module

    output logic clk_ext_selected, // 1 if the main MMMC is running on the external clock

    output wire clk_100,
    output wire clk_100_resn,
    output wire clk_80,
    output wire clk_80_resn,
    output wire clk_10,
    output wire clk_10_resn,

    output wire sysclk_40M
);



    // Reset conditions
    //-----------
    //async_signal_sync  cold_resn_master_sync(.clk(sysclk_in),.async_input(cold_resn_in),.sync_out(cold_resn_in_synced));
    wire all_reset;
    wire mmmc_reset =  resn == 0;
    wire core_locked;


    wire reset_condition = core_locked & resn;


    assign global_resn_o = reset_condition;


    // System input Clocking
    //------------
    //

    // System Clock to 40 Mhz
    wire sys_mmmc_locked;
    //wire sysclk_40M;
    clk_sys_to_40 sys_to_40 (
        .clk_in1(sysclk_in),
        .resetn( !mmmc_reset ), // !mmmc_reset
        .clk_out1(sysclk_40M),
        .locked(sys_mmmc_locked)


    );

    // External Clock Input switchover
    // -----------

    // use a reset resets_synchronizer to detect when the external clock is available
    wire clk_ext_running;
    logic [2:0] clk_ext_switch;




    logic switch_to_primary_clock;
    logic clk_ext_locked;
    logic [1:0] core_locked_temp;
    wire core_locked_negedge = core_locked_temp[1]==1'b1 & core_locked_temp[0]==1'b0;


    wire core_mmmc_resetn = sys_mmmc_locked & !mmmc_reset & !(clk_ext_switch[0]=='b1 & clk_ext_switch[2]==1'b0 ) &  !(clk_ext_locked & !core_locked);
    wire core_mmmc_clksel = !(clk_ext_switch[0] & clk_ext_switch[1]);

    reset_sync #(.RESET_DELAY(15))  clk_ext_detector (.clk(clk_ext),.resn_in(!mmmc_reset & !switch_to_primary_clock),.resn_out(clk_ext_running));

    // When external clock is detected running, we can change the core MMMC clock source but we want to prevent a global reset
    always_ff @(posedge sysclk_40M or negedge sys_mmmc_locked) begin
        if (!sys_mmmc_locked) begin
            clk_ext_switch          <= 'd0;
            core_locked_temp        <= 'd0;
            clk_ext_locked          <= 'd0;
            switch_to_primary_clock <= 'd0;
            clk_ext_selected        <= 'b0;
        end
        else begin

          clk_ext_selected <= !core_mmmc_clksel;

          if (core_mmmc_clksel==1'b0 && clk_ext_locked==1'b1 && !core_locked) begin
              clk_ext_switch <= 'd1;
          end
          // Clock switch will only  start if main pll is locked first
          else if (core_locked || (|clk_ext_switch)) begin
              clk_ext_switch <= {clk_ext_switch[1:0],clk_ext_running};
          end

          if (core_locked && core_mmmc_clksel==1'b0 && !clk_ext_locked) begin
              clk_ext_locked <= 1'b1;
          end
          else if (clk_ext_locked && !core_locked) begin
              clk_ext_locked <= 1'b0;
              switch_to_primary_clock <= 1'b1;
          end
          else if (core_locked && core_mmmc_clksel==1'b1 && switch_to_primary_clock) begin
              switch_to_primary_clock <= 'b0;
          end


        end



    end




    // Core Design Clocking
    // --------------------

    // Sys or External clock switch
    clk_core_extorint_40 intern_or_ext_to_internal (

        .clk_in1   (sysclk_40M),
        .clk_in2   (clk_ext),
        .clk_in_sel(!(clk_ext_switch[0] & clk_ext_switch[1])),
        .resetn    (core_mmmc_resetn),

        // Clock out ports
        .clk_100(clk_100),
        .clk_80 (clk_80),
        .clk_10 (clk_10),

        .locked(core_locked)


    );

    // Module Instance
    /*top_clocking_core_io_uart top_clocking_core_io_uart_I (
        .clk_in1(sysclk_in),

        .clk_100(clk_100),
        .clk_core(clk_core),
        .clk_sample(clk_sample),
        .clk_timestamp(clk_timestamp),
        .clk_uart(clk_uart),
        .locked(pll_locked),
        .power_down(shutdown),
        .resetn(!shutdown)
        );*/


    resets_synchronizer #(
        .CLOCKS(3),
        .RESET_DELAY(15)
    ) resets (
        .async_resn_in(reset_condition),
        .input_clocks({clk_100, clk_80, clk_10}),
        .output_resn({clk_100_resn, clk_80_resn, clk_10_resn}),
        .master_all_reset( )
    );

endmodule
