site_name: Astropix  - ASTEP Documentation
docs_dir: markdown
validation:
  omitted_files: warn
  absolute_links: warn # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn # New in MkDocs 1.6
plugins:
  - drawio:
      toolbar: true # control if hovering on a diagram shows a toolbar for zooming or not (default: true)
      tooltips: true # control if tooltips will be shown (default: true)
      edit: false # control if edit button will be shown in the lightbox view (default: true)
      border: 10 # increase or decrease the border / margin around your diagrams (default: 5)
  - search
  - table-reader:
      data_path: "."
      allow_missing_files: True
  - kroki
  - git-revision-date-localized
  - awesome-pages
  - include-markdown
  - mkdocstrings
  - markdownwavedrom
  - glightbox
repo_url: !ENV [IC_REPO_URL, ""]
repo_name: Astrpopix-Astep
extra_javascript:
  - wd.js
  - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.1.0/skins/default.js
  - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.1.0/wavedrom.min.js
theme:
  name: material
  #custom_dir: custom_theme/
  font:
    text: Baloo Chettan 2
  logo: apix-name.png
  features:
    - navigation.expand
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - toc.integrate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - abbr
  - pymdownx.snippets
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.table
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      title: "Table of Contents"
      toc_depth: "2-5"
      permalink: true
